services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://db:27017/mydatabase
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mongo
    restart: always
    volumes:
      - db-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: mydatabase
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

